services:
  critipixel-database:
    image: postgres:16-alpine
    container_name: critipixel-database
    ports:
      - "5439:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  critipixel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: critipixel-app
    depends_on:
      - critipixel-database
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    ports:
      - "8000:8000"

volumes:
  postgres_db:
    driver: local